# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Aron's page
tagline:             'This is me.'
description:         'A simple blog for you, by me.'
url:                 http://aronmoore.co.uk
baseurl:             /
paginate:            5

# Exert seperator
excerpt_separator: <!--more-->  

# About/contact
author:
  name:              Aron Moore
  url:               https://twitter.com/Azza_M
  email:             aronmoore@aronmoore.co.uk

# Custom vars
version:             1.0.0
